minetest.after(86050, function()
   minetest.chat_send_all("[Server] Nightly reboot in 5 minutes!")
          end)
          minetest.after(86110, function()
               minetest.chat_send_all("[Server] Nightly reboot in 4 minutes!")
          end)
          minetest.after(86170, function()
               minetest.chat_send_all("[Server] Nightly reboot in 3 minutes!")
          end)
          minetest.after(86230, function()
               minetest.chat_send_all("[Server] Nightly reboot in 2 minutes!")
          end)
          minetest.after(86290, function()
               minetest.chat_send_all("[Server] Nightly reboot in 1 minute!")
          end)
          minetest.after(86350, function()
               minetest.chat_send_all("[Server] Nightly reboot in 50 seconds!")
          end)
          minetest.after(86360, function()
               minetest.chat_send_all("[Server] Nightly reboot in 40 seconds!")
          end)
          minetest.after(86370, function()
               minetest.chat_send_all("[Server] Nightly reboot in 30 seconds!")
          end)
          minetest.after(86380, function()
               minetest.chat_send_all("[Server] Nightly reboot in 20 seconds!")
          end)
          minetest.after(86390, function()
               minetest.chat_send_all("[Server] Nightly reboot in 10 seconds!")
          end)
          minetest.after(86400, minetest.request_shutdown)
